### PR TITLE
Course details page

### PR DESCRIPTION
**Pull request by mieliep**

### CODE REVIEW

**Comment by laurenwaller** [comment]
@mieliep It seems like there's a lot missing still, like the last section "Secure your place..." etc. Are you planning to still do that? Might as well only merge once it's complete.

**Comment by mieliep** [comment]
@laurenwaller yes I still need to add those in I just wanted to see if the rest was fine

**Comment by laurenwaller** [comment]
@mieliep Oh cool :) Looks good so far.

**Comment by mieliep** [comment]
@waller I think I have covered everything

**Pull request merged**
